### ISSUE TITLE
ReadTheDocs permission denied

### ISSUE THREAD

**Issue by innisfree** [pbrod/numdifftools#21]
Accessing http://numdifftools.readthedocs.io/ directs to http://numdifftools.readthedocs.io/en/v0.9.14/ and I see the message:

> Permission Denied
> 
> You don't have the proper permissions to view this page. Please contact the owner of this project to request permission.

**Comment by pbrod** [comment]
The documentation for v0.9.14 is no different than v0.9.16.

**Comment by innisfree** [comment]
Accessing http://numdifftools.readthedocs.io/en/v0.9.16/ gives me the same error message.

**Comment by Plancalkuele** [comment]
Same problem here. Would like to read the docs.

**Comment by pbrod** [comment]
The documentation is available from here:
http://numdifftools.readthedocs.io/en/latest/

**Comment by pbrod** [comment]
Won't fix

**Comment by WarrenWeckesser** [comment]
Is it possible to change the link on the pypi page so it points to `http://numdifftools.readthedocs.io/en/latest/`?  If you click on the link text ("http://numdifftools.readthedocs.org/"), you get sent to `http://numdifftools.readthedocs.io/en/v0.9.14/`, which results in the "Permission denied" page.  If you clink on the black and green button labeled "docs latest", you get sent to the desired page `http://numdifftools.readthedocs.io/en/latest/`, but I didn't know that until I had already spent almost 10 minutes trying to figure out what the problem was.

**Comment by innisfree** [comment]
@WarrenWeckesser I had the same experience before I submitted this issue - a silly small thing, but quite frustrating. Please fix.

**Comment by pbrod** [comment]
Fixed in #23 

Thanks @WarrenWeckesser and @innisfree.
