### ISSUE TITLE
Upload proper distutils/setuptools tarball to PyPI

### ISSUE THREAD

**Issue by SoapGentoo** [pbrod/numdifftools#24]
Dear numdifftools developers,
I have recently packaged numdifftools 0.9.16 for Gentoo. One problem is that you do not provide full distutils tarballs on PyPI anymore. Linux distributions heavily rely on being able to run distutils/setuptools on their own systems, be it Gentoo or any other distribution, and hence wheels packages are unworkable for us. So please also upload properly packaged tarballs to PyPI (including all the metadata files such as PKG-INFO) and so. And no, the Github generated tarballs are not sufficient, as they lack the PKG-INFO files, which results in an error. The wider Linux community will greatly appreciate having both tarballs and wheels packages! Thanks for considering my call for help.

**Comment by pbrod** [comment]
Thank you for the notification.  I didn't know about this. The reason why the tarballs was not uploaded last time was because the call "python setup.py sdist" failed. I don't know why it happened, but since I got the wheels right I thought it was sufficient and so decided to not pursue the matter further.  However, I will look into the problem and see what I can do for the next release.

**Comment by pbrod** [comment]
Version 0.9.17 of numdifftools is now available both in wheels and .zip formats.

**Comment by SoapGentoo** [comment]
@pbrod Thanks for being kind to the downstream distributions 😄 .
